import type { PermissionDefinition } from "@/lib/staff/permissionTypes";

export const permissions: PermissionDefinition[] = [
  {
    key: "products.read",
    group: "products",
    label: "Read Products",
    description: "View product records and public product details.",
  },
  {
    key: "products.create",
    group: "products",
    label: "Create Products",
    description: "Create new commerce products.",
  },
  {
    key: "products.edit",
    group: "products",
    label: "Edit Products",
    description: "Update editable product fields and product media.",
  },
  {
    key: "products.archive",
    group: "products",
    label: "Archive Products",
    description: "Archive or deactivate product records.",
  },
  {
    key: "products.cost.read",
    group: "products",
    label: "Read Product Cost",
    description: "View cost and margin information.",
    sensitive: true,
  },
  {
    key: "inventory.read",
    group: "inventory",
    label: "Read Inventory",
    description: "View inventory quantities and locations.",
  },
  {
    key: "inventory.adjust",
    group: "inventory",
    label: "Adjust Inventory",
    description: "Create stock adjustments and cycle counts.",
  },
  {
    key: "inventory.transfer",
    group: "inventory",
    label: "Transfer Inventory",
    description: "Move stock between ASHE TOKUN locations.",
  },
  {
    key: "inventory.locations.manage",
    group: "inventory",
    label: "Manage Inventory Locations",
    description: "Manage stockrooms, retail floor, and fulfillment locations.",
  },
  {
    key: "orders.read",
    group: "orders",
    label: "Read Orders",
    description: "View order records and order history.",
  },
  {
    key: "orders.edit",
    group: "orders",
    label: "Edit Orders",
    description: "Update operational order statuses and notes.",
  },
  {
    key: "orders.cancel",
    group: "orders",
    label: "Cancel Orders",
    description: "Cancel eligible orders and restore inventory.",
  },
  {
    key: "orders.refund",
    group: "orders",
    label: "Refund Orders",
    description: "Process refund workflows.",
    sensitive: true,
  },
  {
    key: "customers.read",
    group: "customers",
    label: "Read Customers",
    description: "View customer profiles and order relationships.",
  },
  {
    key: "customers.create",
    group: "customers",
    label: "Create Customers",
    description: "Create new customer records.",
  },
  {
    key: "customers.edit",
    group: "customers",
    label: "Edit Customers",
    description: "Update customer profiles, notes, and addresses.",
  },
  {
    key: "shipping.read",
    group: "shipping",
    label: "Read Shipping",
    description: "View shipments, packages, addresses, and events.",
  },
  {
    key: "shipping.create",
    group: "shipping",
    label: "Create Shipments",
    description: "Create shipping or pickup fulfillment records.",
  },
  {
    key: "shipping.edit",
    group: "shipping",
    label: "Edit Shipping",
    description: "Update shipment statuses, tracking, packages, and events.",
  },
  {
    key: "shipping.origins.manage",
    group: "shipping",
    label: "Manage Shipping Origins",
    description: "Manage ASHE TOKUN ship-from origins.",
  },
  {
    key: "returns.read",
    group: "returns",
    label: "Read Returns",
    description: "View return and exchange records.",
  },
  {
    key: "returns.create",
    group: "returns",
    label: "Create Returns",
    description: "Create return, exchange, and refund requests.",
  },
  {
    key: "returns.approve",
    group: "returns",
    label: "Approve Returns",
    description: "Approve return and exchange workflows.",
  },
  {
    key: "returns.complete",
    group: "returns",
    label: "Complete Returns",
    description: "Receive returned items and complete return outcomes.",
  },
  {
    key: "pos.access",
    group: "pos",
    label: "Access POS",
    description: "Open the in-store point of sale.",
  },
  {
    key: "pos.checkout",
    group: "pos",
    label: "Complete Checkout",
    description: "Complete local or live POS sales.",
  },
  {
    key: "reports.sales",
    group: "reports",
    label: "Sales Reports",
    description: "View sales and revenue reporting.",
    sensitive: true,
  },
  {
    key: "reports.inventory",
    group: "reports",
    label: "Inventory Reports",
    description: "View inventory reporting and stock risk.",
  },
  {
    key: "staff.read",
    group: "staff",
    label: "Read Staff",
    description: "View employee records and access state.",
  },
  {
    key: "staff.create",
    group: "staff",
    label: "Create Staff",
    description: "Create employee records.",
    ownerCritical: true,
  },
  {
    key: "staff.edit",
    group: "staff",
    label: "Edit Staff",
    description: "Edit employee records and lifecycle state.",
    ownerCritical: true,
  },
  {
    key: "staff.reset_pin",
    group: "staff",
    label: "Reset Staff PIN",
    description: "Set temporary PINs and revoke sessions.",
    ownerCritical: true,
  },
  {
    key: "staff.permissions.manage",
    group: "staff",
    label: "Manage Permissions",
    description: "Grant, revoke, and clone staff permissions.",
    ownerCritical: true,
  },
  {
    key: "settings.company",
    group: "settings",
    label: "Company Settings",
    description: "Manage ASHE TOKUN company configuration.",
  },
  {
    key: "settings.security",
    group: "settings",
    label: "Security Settings",
    description: "Manage authentication and security settings.",
    ownerCritical: true,
  },
  {
    key: "accounting.read",
    group: "accounting",
    label: "Read Accounting",
    description: "View accounting and payout records.",
    sensitive: true,
  },
  {
    key: "accounting.refunds",
    group: "accounting",
    label: "Accounting Refunds",
    description: "Review financial refund workflows.",
    sensitive: true,
  },
  {
    key: "vendors.read",
    group: "vendors",
    label: "Read Vendors",
    description: "View brands, vendors, suppliers, and manufacturer records.",
  },
  {
    key: "vendors.edit",
    group: "vendors",
    label: "Edit Vendors",
    description: "Update vendor, supplier, and brand records.",
  },
  {
    key: "gift_cards.read",
    group: "gift_cards",
    label: "Read Gift Cards",
    description: "View gift card records.",
  },
  {
    key: "gift_cards.issue",
    group: "gift_cards",
    label: "Issue Gift Cards",
    description: "Create or adjust gift card records.",
  },
  {
    key: "store_credit.read",
    group: "store_credit",
    label: "Read Store Credit",
    description: "View store credit records.",
  },
  {
    key: "store_credit.issue",
    group: "store_credit",
    label: "Issue Store Credit",
    description: "Issue store credit from approved workflows.",
  },
  {
    key: "notifications.read",
    group: "notifications",
    label: "Read Notifications",
    description: "View notification history and templates.",
  },
  {
    key: "notifications.send",
    group: "notifications",
    label: "Send Notifications",
    description: "Send customer or operational notifications.",
  },
];

export const permissionKeys = permissions.map((permission) => permission.key);
