import type { PermissionKey, StaffRole } from "@/lib/staff/permissionTypes";

export type RoleTemplate = {
  role: StaffRole;
  label: string;
  description: string;
  permissions: PermissionKey[];
};

const staffSelfTimekeeperPermissions: PermissionKey[] = [
  "timekeeper.clock_self",
  "timekeeper.view_own",
];

const managerTimekeeperPermissions: PermissionKey[] = [
  "timekeeper.clock_self",
  "timekeeper.view_own",
  "timekeeper.view_team",
  "timekeeper.view_all",
  "timekeeper.correct_punch",
  "timekeeper.add_missed_punch",
  "timekeeper.review_timecard",
  "timekeeper.approve_timecard",
  "timekeeper.reopen_timecard",
  "timekeeper.resolve_exception",
];

const assistantManagerTimekeeperPermissions: PermissionKey[] = [
  "timekeeper.clock_self",
  "timekeeper.view_own",
  "timekeeper.view_team",
  "timekeeper.correct_punch",
  "timekeeper.add_missed_punch",
  "timekeeper.review_timecard",
  "timekeeper.resolve_exception",
];

const allTimekeeperPermissions: PermissionKey[] = [
  ...managerTimekeeperPermissions,
  "timekeeper.manage_settings",
  "timekeeper.export",
];

const allPayrollPermissions: PermissionKey[] = [
  "payroll.view",
  "payroll.manage",
  "payroll.export",
  "payroll.approve",
  "payroll.close",
  "payroll.reopen",
  "payroll.generate_package",
];

const ownerPermissions: PermissionKey[] = [
  "products.read",
  "products.create",
  "products.edit",
  "products.archive",
  "products.cost.read",
  "inventory.read",
  "inventory.adjust",
  "inventory.transfer",
  "inventory.locations.manage",
  "orders.read",
  "orders.edit",
  "orders.cancel",
  "orders.refund",
  "customers.read",
  "customers.create",
  "customers.edit",
  "shipping.read",
  "shipping.create",
  "shipping.edit",
  "shipping.origins.manage",
  "schedule.view_own",
  "schedule.view_team",
  "schedule.view_all",
  "schedule.create",
  "schedule.edit",
  "schedule.publish",
  "schedule.archive",
  "schedule.manage_availability",
  "schedule.manage_time_off",
  "schedule.approve_time_off",
  "schedule.override_conflicts",
  ...allTimekeeperPermissions,
  ...allPayrollPermissions,
  "returns.read",
  "returns.create",
  "returns.approve",
  "returns.complete",
  "pos.access",
  "pos.checkout",
  "reports.sales",
  "reports.inventory",
  "staff.read",
  "staff.create",
  "staff.edit",
  "staff.reset_pin",
  "staff.permissions.manage",
  "ownership.transfer",
  "ownership.assign_owner",
  "ownership.remove_last_owner",
  "system.master_recovery",
  "settings.company",
  "settings.security",
  "accounting.read",
  "accounting.refunds",
  "vendors.read",
  "vendors.edit",
  "gift_cards.read",
  "gift_cards.issue",
  "store_credit.read",
  "store_credit.issue",
  "notifications.read",
  "notifications.send",
  "audit.read",
];

const managingPartnerPermissions: PermissionKey[] = ownerPermissions.filter(
  (permission) =>
    ![
      "ownership.transfer",
      "ownership.assign_owner",
      "ownership.remove_last_owner",
      "system.master_recovery",
    ].includes(permission),
);

const storeManagerPermissions: PermissionKey[] = [
  "products.read",
  "products.create",
  "products.edit",
  "inventory.read",
  "inventory.adjust",
  "inventory.transfer",
  "orders.read",
  "orders.edit",
  "orders.cancel",
  "customers.read",
  "customers.create",
  "customers.edit",
  "shipping.read",
  "shipping.create",
  "shipping.edit",
  "schedule.view_own",
  "schedule.view_team",
  "schedule.view_all",
  "schedule.create",
  "schedule.edit",
  "schedule.publish",
  "schedule.manage_availability",
      "schedule.manage_time_off",
      "schedule.approve_time_off",
      "schedule.override_conflicts",
      ...managerTimekeeperPermissions,
      "payroll.view",
      "payroll.manage",
      "payroll.approve",
      "payroll.export",
      "returns.read",
  "returns.create",
  "returns.approve",
  "returns.complete",
  "pos.access",
  "pos.checkout",
  "reports.sales",
  "reports.inventory",
  "staff.read",
  "staff.create",
  "staff.edit",
  "staff.reset_pin",
  "vendors.read",
  "gift_cards.read",
  "gift_cards.issue",
  "store_credit.read",
  "store_credit.issue",
  "notifications.read",
  "notifications.send",
  "audit.read",
];

export const roleTemplates: Record<StaffRole, RoleTemplate> = {
  owner: {
    role: "owner",
    label: "Owner",
    description:
      "Legal ownership, full operations, governance, and master recovery authority.",
    permissions: ownerPermissions,
  },
  managing_partner: {
    role: "managing_partner",
    label: "Managing Partner",
    description:
      "Executive operations authority with Owner-level operational access except reserved ownership governance.",
    permissions: managingPartnerPermissions,
  },
  store_manager: {
    role: "store_manager",
    label: "Store Manager",
    description: "Broad store operations access without owner governance control.",
    permissions: storeManagerPermissions,
  },
  assistant_manager: {
    role: "assistant_manager",
    label: "Assistant Manager",
    description:
      "Delegated floor leadership for sales, customers, scheduling support, and daily operations.",
    permissions: [
      "products.read",
      "inventory.read",
      "orders.read",
      "orders.edit",
      "customers.read",
      "customers.create",
      "customers.edit",
      "shipping.read",
      "schedule.view_own",
      "schedule.view_team",
      "schedule.edit",
      "schedule.manage_availability",
      "schedule.manage_time_off",
      ...assistantManagerTimekeeperPermissions,
      "payroll.view",
      "returns.read",
      "returns.create",
      "pos.access",
      "pos.checkout",
      "reports.inventory",
      "staff.read",
      "vendors.read",
      "gift_cards.read",
      "store_credit.read",
      "notifications.read",
    ],
  },
  manager: {
    role: "manager",
    label: "Store Manager",
    description:
      "Legacy manager role retained for existing staff records; use Store Manager for new assignments.",
    permissions: storeManagerPermissions,
  },
  cashier: {
    role: "cashier",
    label: "Cashier",
    description: "Fast checkout, customer lookup, and order lookup access.",
    permissions: [
      "products.read",
      "orders.read",
      "customers.read",
      "customers.create",
      "pos.access",
      "pos.checkout",
      "schedule.view_own",
      "schedule.manage_availability",
      "schedule.manage_time_off",
      ...staffSelfTimekeeperPermissions,
      "gift_cards.read",
      "store_credit.read",
    ],
  },
  inventory: {
    role: "inventory",
    label: "Inventory Specialist",
    description: "Inventory control and catalog lookup without accounting access.",
    permissions: [
      "products.read",
      "inventory.read",
      "inventory.adjust",
      "inventory.transfer",
      "inventory.locations.manage",
      "schedule.view_own",
      "schedule.manage_availability",
      "schedule.manage_time_off",
      ...staffSelfTimekeeperPermissions,
      "reports.inventory",
      "vendors.read",
    ],
  },
  fulfillment: {
    role: "fulfillment",
    label: "Shipping & Fulfillment",
    description: "Order fulfillment, shipping, pickup, and return receiving access.",
    permissions: [
      "products.read",
      "inventory.read",
      "orders.read",
      "shipping.read",
      "shipping.create",
      "shipping.edit",
      "schedule.view_own",
      "schedule.manage_availability",
      "schedule.manage_time_off",
      ...staffSelfTimekeeperPermissions,
      "returns.read",
      "returns.complete",
      "customers.read",
    ],
  },
  customer_service: {
    role: "customer_service",
    label: "Customer Service",
    description: "Customer support, order review, returns, and service notes.",
    permissions: [
      "products.read",
      "orders.read",
      "orders.edit",
      "customers.read",
      "customers.create",
      "customers.edit",
      "schedule.view_own",
      "schedule.manage_availability",
      "schedule.manage_time_off",
      ...staffSelfTimekeeperPermissions,
      "returns.read",
      "returns.create",
      "notifications.read",
      "notifications.send",
    ],
  },
  accounting: {
    role: "accounting",
    label: "Accounting",
    description: "Financial review and refund accounting without stock control.",
    permissions: [
      "orders.read",
      "orders.refund",
      "reports.sales",
      "customers.read",
      "schedule.view_own",
      "schedule.view_all",
      "timekeeper.view_own",
      "timekeeper.view_all",
      "timekeeper.export",
      "payroll.view",
      "payroll.export",
      "payroll.manage",
      "payroll.approve",
      "payroll.close",
      "payroll.reopen",
      "payroll.generate_package",
      "accounting.read",
      "accounting.refunds",
      "vendors.read",
      "gift_cards.read",
      "store_credit.read",
    ],
  },
  marketing_ecommerce: {
    role: "marketing_ecommerce",
    label: "Marketing & E-Commerce",
    description: "Online catalog, media, marketing, and notification workflows.",
    permissions: [
      "products.read",
      "products.create",
      "products.edit",
      "orders.read",
      "customers.read",
      "schedule.view_own",
      "schedule.manage_availability",
      "schedule.manage_time_off",
      ...staffSelfTimekeeperPermissions,
      "reports.sales",
      "vendors.read",
      "notifications.read",
      "notifications.send",
    ],
  },
};

export const roleTemplateList = Object.values(roleTemplates);
