import type { PermissionKey, StaffRole } from "@/lib/staff/permissionTypes";

export type RoleTemplate = {
  role: StaffRole;
  label: string;
  description: string;
  permissions: PermissionKey[];
};

const ownerPermissions: PermissionKey[] = [
  "products.read",
  "products.create",
  "products.edit",
  "products.archive",
  "products.cost.read",
  "inventory.read",
  "inventory.adjust",
  "inventory.transfer",
  "inventory.locations.manage",
  "orders.read",
  "orders.edit",
  "orders.cancel",
  "orders.refund",
  "customers.read",
  "customers.create",
  "customers.edit",
  "shipping.read",
  "shipping.create",
  "shipping.edit",
  "shipping.origins.manage",
  "schedule.view_own",
  "schedule.view_team",
  "schedule.view_all",
  "schedule.create",
  "schedule.edit",
  "schedule.publish",
  "schedule.archive",
  "schedule.manage_availability",
  "schedule.manage_time_off",
  "schedule.approve_time_off",
  "schedule.override_conflicts",
  "returns.read",
  "returns.create",
  "returns.approve",
  "returns.complete",
  "pos.access",
  "pos.checkout",
  "reports.sales",
  "reports.inventory",
  "staff.read",
  "staff.create",
  "staff.edit",
  "staff.reset_pin",
  "staff.permissions.manage",
  "settings.company",
  "settings.security",
  "accounting.read",
  "accounting.refunds",
  "vendors.read",
  "vendors.edit",
  "gift_cards.read",
  "gift_cards.issue",
  "store_credit.read",
  "store_credit.issue",
  "notifications.read",
  "notifications.send",
];

export const roleTemplates: Record<StaffRole, RoleTemplate> = {
  owner: {
    role: "owner",
    label: "Owner",
    description: "Full operational and security access for ASHE TOKUN ownership.",
    permissions: ownerPermissions,
  },
  manager: {
    role: "manager",
    label: "Manager",
    description: "Broad store operations access without owner security control.",
    permissions: [
      "products.read",
      "products.create",
      "products.edit",
      "inventory.read",
      "inventory.adjust",
      "inventory.transfer",
      "orders.read",
      "orders.edit",
      "orders.cancel",
      "customers.read",
      "customers.create",
      "customers.edit",
      "shipping.read",
      "shipping.create",
      "shipping.edit",
      "schedule.view_own",
      "schedule.view_team",
      "schedule.view_all",
      "schedule.create",
      "schedule.edit",
      "schedule.publish",
      "schedule.manage_availability",
      "schedule.manage_time_off",
      "schedule.approve_time_off",
      "schedule.override_conflicts",
      "returns.read",
      "returns.create",
      "returns.approve",
      "returns.complete",
      "pos.access",
      "pos.checkout",
      "reports.sales",
      "reports.inventory",
      "staff.read",
      "staff.create",
      "staff.edit",
      "staff.reset_pin",
      "vendors.read",
      "gift_cards.read",
      "gift_cards.issue",
      "store_credit.read",
      "store_credit.issue",
      "notifications.read",
      "notifications.send",
    ],
  },
  cashier: {
    role: "cashier",
    label: "Cashier",
    description: "Fast checkout, customer lookup, and order lookup access.",
    permissions: [
      "products.read",
      "orders.read",
      "customers.read",
      "customers.create",
      "pos.access",
      "pos.checkout",
      "schedule.view_own",
      "schedule.manage_availability",
      "schedule.manage_time_off",
      "gift_cards.read",
      "store_credit.read",
    ],
  },
  inventory: {
    role: "inventory",
    label: "Inventory Specialist",
    description: "Inventory control and catalog lookup without accounting access.",
    permissions: [
      "products.read",
      "inventory.read",
      "inventory.adjust",
      "inventory.transfer",
      "inventory.locations.manage",
      "schedule.view_own",
      "schedule.manage_availability",
      "schedule.manage_time_off",
      "reports.inventory",
      "vendors.read",
    ],
  },
  fulfillment: {
    role: "fulfillment",
    label: "Shipping & Fulfillment",
    description: "Order fulfillment, shipping, pickup, and return receiving access.",
    permissions: [
      "products.read",
      "inventory.read",
      "orders.read",
      "shipping.read",
      "shipping.create",
      "shipping.edit",
      "schedule.view_own",
      "schedule.manage_availability",
      "schedule.manage_time_off",
      "returns.read",
      "returns.complete",
      "customers.read",
    ],
  },
  customer_service: {
    role: "customer_service",
    label: "Customer Service",
    description: "Customer support, order review, returns, and service notes.",
    permissions: [
      "products.read",
      "orders.read",
      "orders.edit",
      "customers.read",
      "customers.create",
      "customers.edit",
      "schedule.view_own",
      "schedule.manage_availability",
      "schedule.manage_time_off",
      "returns.read",
      "returns.create",
      "notifications.read",
      "notifications.send",
    ],
  },
  accounting: {
    role: "accounting",
    label: "Accounting",
    description: "Financial review and refund accounting without stock control.",
    permissions: [
      "orders.read",
      "orders.refund",
      "reports.sales",
      "customers.read",
      "schedule.view_own",
      "schedule.view_all",
      "accounting.read",
      "accounting.refunds",
      "vendors.read",
      "gift_cards.read",
      "store_credit.read",
    ],
  },
  marketing_ecommerce: {
    role: "marketing_ecommerce",
    label: "Marketing & E-Commerce",
    description: "Online catalog, media, marketing, and notification workflows.",
    permissions: [
      "products.read",
      "products.create",
      "products.edit",
      "orders.read",
      "customers.read",
      "schedule.view_own",
      "schedule.manage_availability",
      "schedule.manage_time_off",
      "reports.sales",
      "vendors.read",
      "notifications.read",
      "notifications.send",
    ],
  },
};

export const roleTemplateList = Object.values(roleTemplates);
